refactor:  util 분리
uoslife/server-meeting pull request #20
Opened 2023-06-06 10:42 UTC by marsboy02

## 변경사항
- validator를 분리했습니다.
- tranaction를 추가했습니다.

2023-06-06 11:07 UTC, pasly0920 requested changes
고생하셨습니다.
아래 내용들 수정 부탁드리고 CodeCov 기반으로 Test 되지 않은 부분이 있다면 추가적인 Test Code 부탁드립니다.

2023-06-06 11:07 UTC, pasly0920 commented on src/main/kotlin/uoslife/servermeeting/domain/user/domain/service/UserService.kt
> +    private val userValidator: UserValidator,
User Domain 내에 위치하고 있으므로, userValidator가 아니라 validator로 선언해도 괜찮을 것 같습니다.

2023-06-06 11:07 UTC, pasly0920 commented on src/main/kotlin/uoslife/servermeeting/domain/user/domain/util/UserValidator.kt
> +    }
kakaoTalkId 같은 경우 Reset 뿐만 아니라 아직 입력하지 않은 경우도 포함되지 않나요?
해당 경우 역시 존재한다면 alreadyReset보다는 다른 Naming을 사용하는 게 더 좋을 것 같습니다.

2023-06-07 04:27 UTC, marsboy02 commented on src/main/kotlin/uoslife/servermeeting/domain/user/domain/dao/UserPutDao.kt
> -@Transactional
transactional 어노테이션이 쓰인 메서드 내부에서는 트랜잭션으로 관리되고 있기 때문에 Dao에서는 명시적으로 호출을 제외했습니다.
레퍼런스 찾아보았는데 서비스 계층에 두는 것이 일반적인 것 같네요
[참고1] : https://stackoverflow.com/questions/1079114/where-does-the-transactional-annotation-belong
[참고2] : https://medium.com/webeveloper/transactional-%EC%9D%80-%EC%96%B4%EB%8A%90-layer-%EC%97%90-%EB%91%90%EB%8A%94%EA%B2%8C-%EB%A7%9E%EC%9D%84%EA%B9%8C-807f50610f0b

2023-06-07 04:29 UTC, marsboy02 commented on src/main/kotlin/uoslife/servermeeting/domain/user/domain/util/UserValidator.kt
> +    }
그렇네요 함수명이 애매한 것 같네요 수정하겠습니다.

2023-06-07 04:39 UTC, marsboy02 commented on src/main/kotlin/uoslife/servermeeting/domain/user/domain/service/UserService.kt
> +    private val userValidator: UserValidator,
@Component 혹은 @Bean 어노테이션이 있으면 Spring에서 스프링 컨테이너에 빈으로 등록하게 됩니다. 

Validator로 처음에 개발을 진행했는데 스프링 컨테이너에 중복된 이름의 문제로 에러가 발생했습니다. Component 어노테이션에 명시적으로 컨테이너 이름을 설정해줄 수 있는 걸로 알지만, userValidator라는 이름을 선언했습니다.

2023-06-07 05:46 UTC, pasly0920 commented on src/main/kotlin/uoslife/servermeeting/domain/user/domain/dao/UserPutDao.kt
> -@Transactional
이 부분은 저도 모호하게 알고 있었네요 좋습니다

2023-06-07 07:04 UTC, marsboy02 commented on src/main/kotlin/uoslife/servermeeting/domain/user/domain/service/UserService.kt
> +    private val userValidator: UserValidator,
이 부분은 @Component에 명시적으로 컨테이너명을 사용하도록 고쳐보겠습니다.  그게 깔끔할 듯 싶네요.

2023-06-07 09:40 UTC, pasly0920 approved these changes
LGTM~

2023-06-07 10:03 UTC, merged