refactor: 유저 도메인 request 스키마 추가
uoslife/server-meeting pull request #64
Opened 2024-03-20 13:32 UTC by UDADDY

# 설명
UserUpdateRequest DTO 스키마 추가 했습니다.

# 토의 내용
`@Schema(description = "흡연 여부", example = "[FALSE]") val smoking: SmokingType?,`
`@Schema(description = "동물상", example = "[DOG]") val spiritAnimal: List<SpiritAnimalType>?,`
enum type일 경우 리스트 타입을 어떻게 표현해야 할지 모르겠습니다. 리스트는 {DOG}으로 표현하는 게 좋을까요?

2024-03-20 23:24 UTC, sktmdgus1212 requested changes
example만 정확하게 명시하면 merge해도 좋을 것 같습니다:)

2024-03-20 23:24 UTC, sktmdgus1212 commented on src/main/kotlin/uoslife/servermeeting/user/api/UserApi.kt
> +    @Operation(summary = "User 정보 조회", description = "토큰을 통해서 User의 정보를 조회합니다. row가 없다면 생성합니다.")
해당 api 사용하나요? 사용 안하면 삭제해도 될 것 같습니다

2024-03-20 23:24 UTC, sktmdgus1212 commented on src/main/kotlin/uoslife/servermeeting/user/dto/request/UserUpdateRequest.kt
> +    @Schema(description = "성별", example = "[MALE, FEMALE]") @field:NotNull val gender: GenderType,
List<GenderType>이 아니므로 `example  = MALE`로 바꿔도 될 것 같습니다~

2024-03-20 23:24 UTC, sktmdgus1212 commented on src/main/kotlin/uoslife/servermeeting/user/dto/request/UserUpdateRequest.kt
> +    @Schema(description = "학생 타입(학부생, 대학원생, 졸업생", example = "[UNDERGRADUATE]")
마찬가지로 List가 아닌 enum type은 괄호 제외하고 작성하면 좋을 것 같습니다

2024-03-20 23:24 UTC, sktmdgus1212 commented on src/main/kotlin/uoslife/servermeeting/user/dto/request/UserUpdateRequest.kt
> +    @Schema(description = "이름", example = "[NO_RELIGION]") val drinkingMin: Int?,
example이 밀려서 입력된 것 같습니다

2024-03-21 08:27 UTC, UDADDY commented on src/main/kotlin/uoslife/servermeeting/user/api/UserApi.kt
> +    @Operation(summary = "User 정보 조회", description = "토큰을 통해서 User의 정보를 조회합니다. row가 없다면 생성합니다.")
제가 로컬에서 토큰이 잘 발급 됐나 테스트할 때 사용하는데 삭제해야 하나요.....??

2024-03-21 08:29 UTC, UDADDY commented on src/main/kotlin/uoslife/servermeeting/user/dto/request/UserUpdateRequest.kt
> +    @Schema(description = "이름", example = "[NO_RELIGION]") val drinkingMin: Int?,
반영하였습니다~~

2024-03-21 08:32 UTC, UDADDY commented on src/main/kotlin/uoslife/servermeeting/user/dto/request/UserUpdateRequest.kt
> +    @Schema(description = "성별", example = "[MALE, FEMALE]") @field:NotNull val gender: GenderType,
반영하였습니다.

2024-03-21 08:33 UTC, UDADDY commented on src/main/kotlin/uoslife/servermeeting/user/dto/request/UserUpdateRequest.kt
> +    @Schema(description = "학생 타입(학부생, 대학원생, 졸업생", example = "[UNDERGRADUATE]")
반영하였습니다.

2024-03-21 08:56 UTC, sktmdgus1212 commented on src/main/kotlin/uoslife/servermeeting/user/api/UserApi.kt
> +    @Operation(summary = "User 정보 조회", description = "토큰을 통해서 User의 정보를 조회합니다. row가 없다면 생성합니다.")
아 사용되지 않는 api 인줄 알았습니다
그런데 토큰 발급은 다른 api로 확인 가능하지 않나요?

2024-03-21 09:11 UTC, UDADDY commented on src/main/kotlin/uoslife/servermeeting/user/api/UserApi.kt
> +    @Operation(summary = "User 정보 조회", description = "토큰을 통해서 User의 정보를 조회합니다. row가 없다면 생성합니다.")
가능하지만 DB에 유저가 잘 들어갔는지 확인하고 싶어서 남겨뒀습니다.

2024-03-21 09:11 UTC, merged