refactor: java mail에서 aws ses로 변경
uoslife/server-meeting pull request #69
Opened 2024-03-24 13:49 UTC by UDADDY

설정 파일 건드린 게 없는데 막 바뀌어 있네요;;;
말고는 AwsConfig에서 현재 로컬 aws 액세스 키와 시크릿 키를 주입해서 SesClient를 생성합니다.
서버가 올라가는대로 assume-role을 사용해서 가변적으로 키를 주입 받도록 변경할 예정입니다.

2024-03-24 23:23 UTC, sktmdgus1212 requested changes
불필요한 부분 점검 부탁드립니다

2024-03-24 23:23 UTC, sktmdgus1212 commented on q
> +  dev/season4[m
해당 파일 불필요하므로 삭제해도 될 것 같습니다

2024-03-24 23:23 UTC, sktmdgus1212 commented on src/main/resources/db/migration/V10_set_jsonb_in_meeting_team_instead_of_preference_and_information.sql
> +ALTER TABLE "meeting_team"
V10~14까지 불필요한 파일이므로 삭제해도 될 것 같습니다

2024-03-24 23:23 UTC, sktmdgus1212 commented on src/main/kotlin/uoslife/servermeeting/user/api/UserApi.kt
> +class UserApi(private val userService: UserService, private val userRepository: UserRepository) {
해당 부분 사용안해서 삭제한 것 같은데 필요한가요??

2024-03-25 01:04 UTC, UDADDY commented on q
> +  dev/season4[m
뭔지 몰랐지만 삭제했습니다.

2024-03-25 01:05 UTC, UDADDY commented on src/main/resources/db/migration/V10_set_jsonb_in_meeting_team_instead_of_preference_and_information.sql
> +ALTER TABLE "meeting_team"
넵 삭제했습니다.

2024-03-25 01:05 UTC, UDADDY commented on src/main/kotlin/uoslife/servermeeting/user/api/UserApi.kt
> +class UserApi(private val userService: UserService, private val userRepository: UserRepository) {
사용 안 해서 삭제했습니다.

2024-03-25 01:13 UTC, merged